[tasks.install]
run = "pnpm install --filter kondis-server --frozen-lockfile"

[tasks.build]
env._.path = "./node_modules/.bin"
run = "tsc -p tsconfig.build.json && tsc-alias -p tsconfig.build.json"

[tasks."test-medium"]
env._.path = "./node_modules/.bin"
run = "vitest --config test/vitest.config.medium.mjs"

[tasks.format]
env._.path = "./node_modules/.bin"
run = "prettier --check ."

[tasks."format-fix"]
env._.path = "./node_modules/.bin"
run = "prettier --write ."

[tasks.lint]
env._.path = "./node_modules/.bin"
run = "eslint \"{src,test}/**/*.ts\" --max-warnings 0"

[tasks."lint-fix"]
run = { task = "lint --fix" }

[tasks.check]
env._.path = "./node_modules/.bin"
run = "tsc --noEmit"

[tasks.test]
env._.path = "./node_modules/.bin"
run = "vitest run"

[tasks.migrations]
env._.path = "./node_modules/.bin"
usage = '''
arg "<command>" help="Migration operation" {
  choices "create" "run" "revert"
}
arg "[name]" help="Name for a new migration"
'''
run = 'node -r @swc-node/register src/bin/migrations.ts "${usage_command?}" "${usage_name:-}"'

[tasks.migrate]
run = { task = "migrations", args = ["run"] }

[tasks."db-codegen"]
env._.path = "./node_modules/.bin"
run = "kysely-codegen --dialect postgres --out-file src/db/schema.generated.ts"

[tasks."sync-open-api"]
env._.path = "./node_modules/.bin"
run = "node -r @swc-node/register src/bin/sync-open-api.ts"

[tasks."third-party-licenses"]
env._.path = "./node_modules/.bin"
run = "node -r @swc-node/register src/bin/generate-third-party-notices.ts"
