[tasks.install]
run = "pnpm install --filter kondis --frozen-lockfile"

[tasks.build]
env._.path = "./node_modules/.bin"
run = "nest build"

[tasks.format]
env._.path = "./node_modules/.bin"
run = "prettier --check ."

[tasks."format-fix"]
env._.path = "./node_modules/.bin"
run = "prettier --write ."

[tasks.lint]
env._.path = "./node_modules/.bin"
run = "eslint \"src/**/*.ts\" \"test/**/*.ts\" --max-warnings 0"

[tasks."lint-fix"]
run = { task = "lint --fix" }

[tasks.check]
env._.path = "./node_modules/.bin"
run = "tsc --noEmit"