services:
  postgres:
    container_name: base_images_postgres
    user: 1000:1001
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PG_MAJOR: 17
        VECTORCHORD_TAG: 1.1.1
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/kondis_db_password
      KONDIS_DB_USERNAME_FILE: /run/secrets/kondis_db_user
      KONDIS_DB_DATABASE_NAME: "database_name"
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ./data:/var/lib/postgresql
    restart: always
    secrets:
      - kondis_db_user
      - kondis_db_password

secrets:
  kondis_db_user:
    file: ./secrets/postgres_username.txt
  kondis_db_password:
    file: ./secrets/postgres_password.txt
