<script lang="ts">
  import CodeBlock from "$lib/components/CodeBlock.svelte";

  const install = `pnpm add @kondis/sdk`;
  const initialize = `import { init } from "@kondis/sdk";

init({
  baseUrl: "https://your-kondis.example/api/v1",
  token: process.env.KONDIS_TOKEN,
});`;
  const usage = `import {
  activityControllerListRecent,
  activityControllerGetById,
} from "@kondis/sdk";

const page = await activityControllerListRecent({ limit: 25 });
const activity = await activityControllerGetById({ id: page.activities[0].id });`;
</script>

<svelte:head>
  <title>TypeScript SDK | Kondis API</title>
</svelte:head>

<article class="page-shell narrow">
  <div class="eyebrow">Generated client</div>
  <h1>Typed all the way to the trail.</h1>
  <p class="lede">
    The Kondis TypeScript SDK is generated by oazapfts from the same OpenAPI
    contract as this site. Every operation becomes a typed function and every
    schema becomes a TypeScript type.
  </p>

  <section class="sdk-install">
    <div>
      <h2>Install</h2>
      <p>
        Add the generated ESM client and its runtime to a Node.js or browser
        project.
      </p>
    </div>
    <CodeBlock code={install} label="terminal" />
  </section>

  <div class="section-heading">
    <h2>Configure once</h2>
    <span>base URL + headers</span>
  </div>
  <p class="prose">
    Set the server URL before making requests. Defaults can be configured
    globally or overridden per operation.
  </p>
  <CodeBlock code={initialize} label="typescript" />

  <div class="section-heading">
    <h2>Call typed operations</h2>
    <span>zero handwritten DTOs</span>
  </div>
  <p class="prose">
    Function names are derived from each OpenAPI <code>operationId</code>.
    Arguments, responses, enumerations, and error unions update whenever the
    server contract changes.
  </p>
  <CodeBlock code={usage} label="typescript" />

  <div class="steps">
    <div class="step">
      <h3>Server decorators define the contract</h3>
      <p>NestJS and nestjs-zod produce the checked-in OpenAPI document.</p>
    </div>
    <div class="step">
      <h3>oazapfts generates the SDK</h3>
      <p>
        The generator emits an ESM fetch client, TypeScript types, enums, and
        request helpers.
      </p>
    </div>
    <div class="step">
      <h3>CI prevents drift</h3>
      <p>
        Pull requests regenerate the schema and SDK and fail if committed output
        differs.
      </p>
    </div>
  </div>

  <div class="next-grid">
    <a class="next-card" href="/endpoints">
      <small>Operations</small>
      <strong>Find an SDK function</strong>
    </a>
    <a
      class="next-card"
      href="https://github.com/konditori/kondis/tree/main/packages/sdk"
    >
      <small>Source</small>
      <strong>Inspect the generated client</strong>
    </a>
  </div>
</article>
